---
- hosts: humhub_server
  become: yes
  become_user: sema
  gather_facts: true

  tasks:
    - name: Ping test to check connectivity
      ansible.builtin.ping:
      
    - name: Stop Apache2 service
      ansible.builtin.service:
        name: apache2
        state: stopped
      become: yes
